#!/usr/bin/env python3
"""Writes docs/narrative/world-facts.md: a short, readable summary of the garden
from world/lawn/layout.json and player/player.gd (places, sizes, route, distances, scale, what Amodu can do)
for the narrative designer, so it never has to read the whole layout.

Run after any layout change:  python3 tools/world_facts.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAYOUT = ROOT / "world/lawn/layout.json"
PLAYER = ROOT / "player/player.gd"
OUT = ROOT / "docs/narrative/world-facts.md"

# Amodu's limits live in code; keep these in step with world/props/heavable.gd.
LIFT_MAX_M = 2.6
PUSH_MAX_M = 5.5


def xz(p):
    return (float(p[0]), float(p[1]))


def real_mm(m, scale):
    """In-game metres to a real-world size."""
    mm = m / scale * 1000.0
    return f"{mm / 10:.1f} cm" if mm >= 10 else f"{mm:.1f} mm"


def compass(a, b):
    dx, dz = b[0] - a[0], b[1] - a[1]
    ang = (math.degrees(math.atan2(dx, -dz)) + 360) % 360  # north = -z
    return ["N", "NE", "E", "SE", "S", "SW", "W", "NW"][int((ang + 22.5) // 45) % 8]


def player_values():
    """Reads Amodu's movement numbers from player/player.gd (@export var name := number)."""
    import re
    vals = {}
    for m in re.finditer(r"@export var (\w+) := (-?[0-9.]+)\b", PLAYER.read_text()):
        vals[m.group(1)] = float(m.group(2))
    return vals


def cell(s):
    return str(s).replace("|", "/").replace("\n", " ")


def main():
    d = json.loads(LAYOUT.read_text())
    meta = d.get("meta", {})
    scale = float(meta.get("world_scale", 360))
    lines = [
        "# World facts (generated)",
        "",
        f"Generated by `tools/world_facts.py` from `world/lawn/layout.json` and `player/player.gd`. **Don't edit by hand**; re-run the tool after a layout change.",
        "",
        "## Scale and rules",
        f"- Everything is ×{scale:g}. Amodu is {meta.get('amodu_height', 1.8)} m in game (5 mm real), **about the same size as the ants**.",
        f"- 1 m in game = {real_mm(1, scale)} real. 10 m = {real_mm(10, scale)}. 100 m = {real_mm(100, scale)}.",
        f"- Amodu's heave: **lift ≤ {LIFT_MAX_M} m, push ≤ {PUSH_MAX_M} m** (object size, in game). Bigger needs leverage, rope or help.",
        f"- Coordinates are [x, z] in metres: +x east, +z south (north is -z). Playable bounds: {meta.get('playable_bounds')}.",
        f"- Setting: {cell(meta.get('setting', ''))}",
        f"- Season and start: {cell(meta.get('season', ''))}; the day starts at {meta.get('default_time', '?')}.",
    ]
    v = player_values()
    g = lambda k: f"{v[k]:g}" if k in v else "?"
    lines += [
        "",
        "## What Amodu can do (from player/player.gd)",
        "He's 1.8 m tall in game. A full-size boy's strength shows in how he moves, not just what he lifts:",
        f"- **Speed:** walk {g('walk_speed')} m/s, jog {g('jog_speed')}, sprint {g('sprint_speed')}; crawl {g('crawl_speed')}; climb {g('climb_speed')} (×{g('climb_sprint_factor')} when hurrying). He climbs up, down and sideways.",
        f"- **Jumps:** a hop of {g('jump_height')} m. A **power jump** (hold, crouch, release) goes **{g('power_jump_min_height')}–{g('power_jump_max_height')} m high and {g('power_jump_min_forward')}–{g('power_jump_max_forward')} m forward**, up to about **{v.get('power_jump_max_height', 0) / 1.8:.0f}× his own height**. A **running leap** reaches {g('run_leap_height')} m high. Landing from {g('slam_min_fall')} m or more sends out a shockwave ({g('slam_radius')} m).",
        f"- **Throw:** {g('throw_speed')} m/s; carrying slows him to ×{g('carry_speed_factor')} and his jump to ×{g('carry_jump_factor')}.",
        f"- **Glide** on a seed puff: {g('glide_speed')} m/s forward, sinking {g('glide_sink')} m/s; after about {g('glide_fresh_time')} s the puff tires and he sinks faster. The breeze carries him.",
        f"- **Swim:** {g('swim_speed')} m/s ({g('swim_sprint_speed')} hurrying) in water deeper than {g('swim_depth')} m; he can jump out of the water.",
        f"- **Call:** a pheromone-style call reaches {g('call_radius')} m.",
        "- Real ants climb and run but don't leap. **Leaping, throwing and gliding are his, not theirs.**",
        "",
        "## Areas",
        "| Area | Centre [x, z] | Size (radii, m) | Role |",
        "|---|---|---|---|",
    ]
    for a in d.get("areas", []):
        lines.append(f"| {a.get('name', a.get('id'))} (`{a.get('id')}`) | {a.get('center')} | {a.get('radii')} | {cell(a.get('role', ''))} |")

    lines += ["", "## Landmarks", "| Landmark | Where [x, z] | Size (m) | Real size | Note |", "|---|---|---|---|---|"]
    for l in d.get("landmarks", []):
        pos = l.get("pos") or l.get("at") or l.get("center")
        size = l.get("size")
        big = max(size) if isinstance(size, list) and size else size
        real = cell(l.get("real") or (real_mm(float(big), scale) if isinstance(big, (int, float)) else ""))
        lines.append(f"| {l.get('name', l.get('id'))} (`{l.get('id')}`) | {pos} | {size} | {real} | {cell(l.get('note', ''))[:160]} |")

    route = d.get("route") or d.get("route_home") or {}
    stages = route.get("stages", []) if isinstance(route, dict) else []
    if stages:
        lines += ["", "## The route (Level 1 stages, in order)", "| # | Stage | At [x, z] | From the last | Why |", "|---|---|---|---|---|"]
        spawn = d.get("spawn", {})
        prev = xz(spawn["pos"]) if "pos" in spawn else None
        total = 0.0
        for i, st in enumerate(stages, 1):
            at = xz(st["at"])
            leg = ""
            if prev is not None:
                dist = math.dist(prev, at)
                total += dist
                leg = f"{dist:.0f} m {compass(prev, at)}"
            prev = at
            lines.append(f"| {i} | {st.get('name', st.get('id'))} | {list(st['at'])} | {leg} | {cell(st.get('why', ''))[:140]} |")
        lines.append(f"\nTotal straight-line route: **{total:.0f} m** (about {total / 4.5 / 60:.1f} min at a 4.5 m/s jog).")

    lines += ["", "## Water"]
    for w in d.get("water", []):
        poly = w.get("polygon", [])
        if poly:
            xs = [p[0] for p in poly]
            zs = [p[1] for p in poly]
            lines.append(f"- **{w.get('name', w.get('id'))}**: x {min(xs):g}–{max(xs):g}, z {min(zs):g}–{max(zs):g} ({max(xs) - min(xs):g} × {max(zs) - min(zs):g} m), depth {w.get('depth')}. {cell(w.get('note', ''))}")

    heav = d.get("heavables", [])
    if isinstance(heav, list) and heav:
        lines += ["", "## Things Amodu can heave", "| Thing | Where | Size (m) | Lift or push | Note |", "|---|---|---|---|---|"]
        for h in heav:
            size = float(h.get("size", 0))
            how = "lift" if size <= LIFT_MAX_M else ("push" if size <= PUSH_MAX_M else "too big")
            lines.append(f"| {h.get('name', h.get('kind'))} | {h.get('pos')} | {size:g} | {how} | {cell(h.get('note', ''))[:120]} |")

    who = d.get("standins", [])
    if who:
        lines += ["", "## Who stands where", "| Name | Where | Kind |", "|---|---|---|"]
        for s in who:
            lines.append(f"| {s.get('name')} | {s.get('pos') or s.get('at')} | {s.get('kind')} |")

    tb = d.get("tree_base", {})
    if tb:
        lines += ["", "## The apple tree's caves (tree_base)"]
        for t in tb.get("tunnels", []):
            pts = t.get("points")
            where = f"{pts[0]} → {pts[-1]}" if pts else ("helix up to y " + str(t.get("helix", {}).get("to_y")))
            lines.append(f"- Tunnel **{t.get('name')}** (`{t.get('id')}`): radius {t.get('radius')} m, {where}")
        for c in tb.get("chambers", []):
            lines.append(f"- Chamber **{c.get('name')}** (`{c.get('id')}`): centre {c.get('center')}, radii {c.get('radii')} m")
        trunk = tb.get("trunk", {})
        if trunk:
            lines.append(f"- Trunk: centre {trunk.get('center')}, radius {trunk.get('radius')} m, height {trunk.get('height')} m ({real_mm(float(trunk.get('height', 0)), scale)} real).")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
